---
language: node_js
node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

before_install:
  - npm config set registry http://registry.npmjs.org/
  - npm config set spin false
  - git config user.name 'travis-build'

install:
  - npm install

script:
  - npm test
